const CurrencyRegion = {
    USD: "US dollar",
    JPY: "Japanese yen",
    BGN: "Bulgarian lev",
    CZK: "Czech koruna",
    DKK: "Danish krone",
    GBP: "Pound sterling",
    HUF: "Hungarian forint",
    PLN: "Polish zloty",
    RON: "Romanian leu",
    SEK: "Swedish krona",
    CHF: "Swiss franc",
    ISK: "Icelandic krona",
    NOK: "Norwegian krone",
    HRK: "Croatian kuna",
    RUB: "Russian rouble",
    TRY: "Turkish lira",
    AUD: "Australian dollar",
    BRL: "Brazilian real",
    CAD: "Canadian dollar",
    CNY: "Chinese yuan renminbi",
    HKD: "Hong Kong dollar",
    IDR: "Indonesian rupiah",
    ILS: "Israeli shekel",
    INR: "Indian rupee",
    KRW: "South Korean won",
    MXN: "Mexican peso",
    MYR: "Malaysian ringgit",
    NZD: "New Zealand dollar",
    PHP: "Philippine piso",
    SGD: "Singapore dollar",
    THB: "Thai baht",
    ZAR: "South African rand",
    EUR: "Euro"
  };

  const CurrencyCountry = {
    USD: "United States",
    JPY: "Japan",
    BGN: "Bulgaria",
    CZK: "Czechia",
    DKK: "Denmark",
    GBP: "United Kingdom",
    HUF: "Hungary",
    PLN: "Poland",
    RON: "Romania",
    SEK: "Sweden",
    CHF: "Switzerland",
    ISK: "Iceland",
    NOK: "Norway",
    HRK: "Croatia",
    RUB: "Russian Federation",
    TRY: "Turkey",
    AUD: "Australia",
    BRL: "Brazil",
    CAD: "Canada",
    CNY: "China",
    HKD: "Hong Kong",
    IDR: "Indonesia",
    ILS: "Israel",
    INR: "India",
    KRW: "Southe Korea",
    MXN: "Mexico",
    MYR: "Malaysia",
    NZD: "New Zealand",
    PHP: "Philippines",
    SGD: "Singapore",
    THB: "Thailand",
    ZAR: "South Africa",
    EUR: "European Union"
  }

  export default {CurrencyRegion, CurrencyCountry};
